### ISSUE TITLE
Installation Prolems package mlat-client_0.2.11_BUSTER_arm64.deb on raspberry pi 3b 64bit bullseye

### ISSUE THREAD

**Issue by KBfly** [abcd567a/mlat-client-package#1]
... during the installation it seems a problem due to dependency of python package?

dpkg -i mlat-client_0.2.11_BUSTER_arm64.deb
Selecting previously unselected package mlat-client.
(Reading database ... 40207 files and directories currently installed.)
Preparing to unpack mlat-client_0.2.11_BUSTER_arm64.deb ...
Unpacking mlat-client (0.2.11) ...
dpkg: dependency problems prevent configuration of mlat-client:
 mlat-client depends on python3 (<< 3.8); however:
  Version of python3 on system is 3.9.2-3.
 mlat-client depends on python3.7:any.

dpkg: error processing package mlat-client (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 mlat-client

-> yes, it's raspi OS bullseye with python 3.9x ...3.7 is to old!?

what ca i do? ...any hints?
thanks,

Karsten

**Comment by abcd567a** [comment]
Mlat client package built for BUSTER wont install on BULLSEYE.

Please built the package right on RPi running "Raspi OS Bullseye" from source code using following procedure:

## PROCEDURE FOR INSTALLING MLAT-CLIENT ON BULLSEYE BY BUILDING MLAT-CLIENT PACKAGE FROM SOURCE CODE


```
## Installed required packages (dependencies and build tools)
sudo apt update -y
sudo apt-get install -y git curl build-essential debhelper python-dev python3-dev

## Downloaded source code
cd /home/pi/ 
git clone https://github.com/mutability/mlat-client.git 

## Built mlat-client's installation package
cd /home/pi/mlat-client 
sudo apt-get install -y dh-python 
sudo dpkg-buildpackage -b -uc 

## Above command took some time to build package. 
## After the package was built, installed it by following command
cd /home/pi/ 
sudo dpkg -i mlat-client_*.deb  

```
**IMPORTANT:**
Before issueing the last command above, **delete the BUSTER package you have downloaded earlier**, else the last command may try to install downloaded Buster package, instead of installing newly built package.

**Comment by abcd567a** [comment]
Mlat client package for bullseye are available now. See here:

https://github.com/abcd567a/mlat-client-package/blob/master/README.md. 

</br></br>

**Comment by KBfly** [comment]
hi,

many many thanks :) ...yes it works!

best regards!

Am Fr., 3. Dez. 2021 um 10:19 Uhr schrieb abcd567a ***@***.***
